import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`name_label\` text DEFAULT 'Name';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`name_placeholder\` text DEFAULT 'John Doe';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`email_label\` text DEFAULT 'Email Address';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`email_placeholder\` text DEFAULT 'john@example.com';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`subject_label\` text DEFAULT 'Subject';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`subject_placeholder\` text DEFAULT 'What do you need help with?';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`message_label\` text DEFAULT 'Message';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`message_placeholder\` text DEFAULT 'Please describe your issue in detail...';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` ADD \`submit_button_text\` text DEFAULT 'Submit Ticket';`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_help_center_cards\` ADD \`link_url\` text;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`name_label\` text DEFAULT 'Name';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`name_placeholder\` text DEFAULT 'John Doe';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`email_label\` text DEFAULT 'Email Address';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`email_placeholder\` text DEFAULT 'john@example.com';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`subject_label\` text DEFAULT 'Subject';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`subject_placeholder\` text DEFAULT 'What do you need help with?';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`message_label\` text DEFAULT 'Message';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`message_placeholder\` text DEFAULT 'Please describe your issue in detail...';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` ADD \`submit_button_text\` text DEFAULT 'Submit Ticket';`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_help_center_cards\` ADD \`link_url\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`name_label\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`name_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`email_label\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`email_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`subject_label\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`subject_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`message_label\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`message_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_ticket_form\` DROP COLUMN \`submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`payload_pages_blocks_help_center_cards\` DROP COLUMN \`link_url\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`name_label\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`name_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`email_label\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`email_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`subject_label\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`subject_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`message_label\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`message_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_ticket_form\` DROP COLUMN \`submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`_payload_pages_v_blocks_help_center_cards\` DROP COLUMN \`link_url\`;`)
}
