// ─────────────────────────────────────────────
//  lib/products.js
//  Product catalogue — single source of truth
// ─────────────────────────────────────────────

var products = [
  {
    id: 1,
    brand: 'KINDARD',
    name: 'Soda Can Hoodie',
    price: 1245,
    orig: null,
    discount: null,
    emoji: '🧥',
    dark: true,
    colors: ['#0a0a0a', '#e8e5e0', '#3a5fa0', '#d4c4a0'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: ['XS', 'S', 'M', 'L'],
    rating: 4.9,
    isNew: true,
    category: 'hoodies',
  },
  {
    id: 2,
    brand: 'KINDARD',
    name: 'Contrast Pick Shirt',
    price: 245,
    orig: null,
    discount: null,
    emoji: '👕',
    dark: false,
    colors: ['#9ecf7a', '#0a0a0a'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    isNew: true,
    category: 'tees',
  },
  {
    id: 3,
    brand: 'KINDARD',
    name: 'Soda Can Tee',
    price: 125,
    orig: null,
    discount: null,
    sold: true,
    emoji: '👕',
    dark: true,
    colors: ['#0a0a0a', '#ffffff'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: [],
    rating: 4.8,
    isNew: false,
    category: 'tees',
  },
  {
    id: 4,
    brand: 'KINDARD',
    name: 'Big Basic Short',
    price: 666,
    orig: 999,
    discount: 23,
    emoji: '🩳',
    dark: false,
    colors: ['#1a2a4a', '#0a0a0a', '#d4c4a0'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.4,
    isNew: false,
    category: 'shorts',
  },
  {
    id: 5,
    brand: 'KINDARD',
    name: 'Eddie Plaid Zip Shirt',
    price: 1399,
    orig: null,
    discount: null,
    emoji: '🧣',
    dark: false,
    colors: ['#8b6f47', '#0a0a0a'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: ['S', 'M', 'L'],
    rating: 4.7,
    isNew: true,
    category: 'tees',
  },
  {
    id: 6,
    brand: 'KINDARD',
    name: 'Big Mesh Polo Sweater',
    price: 2421,
    orig: 2532,
    discount: 10,
    emoji: '🧶',
    dark: false,
    colors: ['#f0ede8', '#0a0a0a'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    avail: ['M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    isNew: false,
    category: 'knits',
  },
];
